compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]
node_compat = true

[build]
command = "npm run build"
[build.environment]
NODE_VERSION = "18.18.0"
NEXT_IGNORE_NODE_VERSION = "true"
SKIP_NEXTJS_NODE_VERSION_CHECK = "true"
SKIP_NEXTJS_NODE_VERSION_WARNING = "true"