name = "flowers-luxe"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat", "nodejs_compat_v2"]

[env.production]
compatibility_flags = ["nodejs_compat", "nodejs_compat_v2"]

[env.preview]
compatibility_flags = ["nodejs_compat", "nodejs_compat_v2"]
