compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]
node_compat = true

# The build command to run
[build]
command = "node cloudflare.js"
[build.environment]
NODE_VERSION = "18.18.0"
NEXT_IGNORE_NODE_VERSION = "true"
SKIP_NEXTJS_NODE_VERSION_CHECK = "true"
SKIP_NEXTJS_NODE_VERSION_WARNING = "true"

# Important: specify the output directory for Pages
pages_build_output_dir = ".next"
